# Site settings
title: "Conductor AI: AI-Guided Development on Rails"
description: >-
  Conductor is an opinionated workflow engine for guiding AI in software engineering. It establishes a set of conventions—"the rails"—for interacting with a Large Language Model (LLM) to solve common development tasks. Stop talking to your AI. Start conducting it.
baseurl: "/conductor-ai" # Assuming it will be hosted on GitHub pages for this repo
url: "https://your-github-username.github.io" # Replace with your GitHub pages URL
github_username: your-github-username # Replace with your GitHub username
github_repo_url: "https://github.com/your-github-username/conductor-ai" # Replace with your repo URL

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
